### ISSUE TITLE
BacPipe GUI running problem

### ISSUE THREAD

**Issue by Rajeefa** [wholeGenomeSequencingAnalysisPipeline/BacPipe#12]
I tried running BacPipe GUI using this command
sudo docker run -it --volume /home/abb/Bacpipe-1.2.6:/mahmed/mnt/mydata --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" mahmed/bacpipe python ./Pipeline.py unix

I get this error
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "./Pipeline.py", line 1868, in <module>
    app = gui("Bacterial Whole Genome Sequencing Analysis Pipeline",'780x800')#,'962x785')#,'569x625')#,'569x625'
  File "/BacPipe/appJar/appjar.py", line 466, in __init__
    self.topLevel = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0"

How can i solve it

**Comment by Rajeefa** [comment]
It was sorted by enabling acess by xhost + but now the problem is my gui dimension is not fit with the ubuntu screen. While running this is being shown in the terminal

2020-08-06 13:38:08,672 appJar:WARNING: Specified dimensions (780x800), less than requested dimensions (1015x850)
2020-08-06 13:38:08,673 appJar:WARNING: Invalid location: 293, -16 - ignoring
How can i change the dimension to show the last section of the BacPipe window.

**Comment by M-Mysara** [comment]
Hi Rajeefa,

Good that you were able to solve the xhost+ issue (would you mind giving more information on your solution so others might benefit from it).

In regards to your question, this can be modified in the Pipeline.py script line 1868
app = gui("Bacterial Whole Genome Sequencing Analysis Pipeline",'780x800')#,'962x785')#,'569x625')#,'569x625'

You could also not define the dimensions (in such case it will use the default).

Mohamed

**Comment by Rajeefa** [comment]
Thanks for the reply.The Bacpipe launched through docker but I still can't run due to sections not visible.I have attached a screen shot of the GUI in my screen.Please go through it and suggest a solution.
~$ xhost +
access control disabled, clients can connect from any host
~$ sudo docker run -it --volume /home/abb/Documents/bacpipe:/mahmed/mnt/mydata -e DISPLAY=$DISPLAY --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" mahmed/bacpipe python ./Pipeline.py unix
2020-08-19 08:09:41,813 appJar:WARNING: Specified dimensions (780x800), less than requested dimensions (1015x935)
2020-08-19 08:09:41,813 appJar:WARNING: Invalid location: 293, -16 - ignoring

The screenshot:
![Bacpipe](https://user-images.githubusercontent.com/28209328/90610334-f28cfe00-e20d-11ea-8646-bc6d873f2365.png)

**Comment by M-Mysara** [comment]
I see what you mean, the easiest solution would be for you to run it as: 

sudo docker run -it --volume /home/abb/Documents/bacpipe:/mahmed/mnt/mydata -e DISPLAY=$DISPLAY --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" mahmed/bacpipe

Then using "vi ./Pipeline.py" you can open the main script and modify it as I proposed above. To save and quit type:

:wq

(check vi documentary if needed https://kb.iu.edu/d/adxz)

Then run the program as:
python ./Pipeline.py unix

With should do the trick.

MM

**Comment by Rajeefa** [comment]
Thankyou for the support.It worked and bacpipe opened. While running the pipeline now a problem is encountered.Iam attaching the screenshot of terminal as well as log.txt ,files_processed.txt and pipeline.log.
The input files i passed as arguments are paired-ends with pairing ones sorted by pairfq.My terminal screenshot:
![gzipbcp](https://user-images.githubusercontent.com/28209328/90691688-6960e000-e27c-11ea-83e5-6147dec756ce.png)
my log.txt:
[log.txt](https://github.com/wholeGenomeSequencingAnalysisPipeline/BacPipe/files/5099425/log.txt)
my pipeline.log:
[pipeline.log](https://github.com/wholeGenomeSequencingAnalysisPipeline/BacPipe/files/5099427/pipeline.log)
my files_processed.txt
[files_processed.txt](https://github.com/wholeGenomeSequencingAnalysisPipeline/BacPipe/files/5099429/files_processed.txt)
Please guide me if any changes need to be made.

**Comment by M-Mysara** [comment]
Hi Rajeefa,

BacPipe takes a "folder" as an input, and reads in all of the fastq files within (identifying automatically the forward and reverse ending with _R1_001.fq.gz and _R2_001.fq.gz).

So make sure that you files are named accordingly (you can rename your files by using unix _rename_ command if you have alot of samples).

In a future versions I will try to make this more generalizable.

Please let me know if everything ran as expected.

MM

**Comment by Rajeefa** [comment]
My samples had been renamed in the format mentioned (e.g. aR182_R1_001.fq.gz and aR182_R2_001.fq.gz) but same error is being reported.

**Comment by Rajeefa** [comment]
My samples had been renamed in the format mentioned (e.g. aR182_R1_001.fq.gz and aR182_R2_001.fq.gz) but same error is being reported.

**Comment by M-Mysara** [comment]
Hi Rajeefa,

I think the problem with how you input your files, in essence you should select the PATH where you files at. 

For instance, if you forward and reverse fastq files are in: /mahmed/mnt/mydata/aR182_R1_ you should select this as input path (the folder itself). 
If this is the case, BacPipe would expect to have in /mahmed/mnt/mydata/aR182_R1_ the following:
SOMETHING_R1_001.fq.gz and SOMETHING_R2_001.fq.gz
You could have as much fastq as possible (As long as they are paired). 
Please also make sure that you input directory contains nothing but those fastq files (meaning no other fasta, fsa, faa, fa, etc files).
Did that resolve the problem?
Mohamed
