### ISSUE TITLE
WGS bacteriophages denovo analysis?

### ISSUE THREAD

**Issue by marwa38** [wholeGenomeSequencingAnalysisPipeline/BacPipe#17]
Hello
Does BacPipe analyze the whole genome sequenced bacteriophages? as I want to reproduce this denovo study: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4429339/
Thanks
Marwa

**Comment by M-Mysara** [comment]
Dear Marwa,

BacPipe is dedicated for Bacterial whole genome sequencing, thus won't be
optimal for bacteriophages.

Sincerely
Mohamed

**Comment by marwa38** [comment]
Cheers Mohamed
